server:
  port: 8080
  contextPath: /article-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tpns
    username: tpns
    password: tpns
    driver-class-name: org.postgresql.Driver
    max-active: 80

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
